# Generated by Django 5.2.17 on 2026-10-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformance',
            name='category',
            field=models.CharField(choices=[('documentation', 'Documentation'), ('controls', 'Internal Controls'), ('operations', 'Operations'), ('financial_records', 'Financial Records'), ('reporting', 'Reporting'), ('compliance', 'Compliance'), ('it_systems', 'IT Systems'), ('other', 'Other')], default='other', help_text='Used for cross-engagement pattern detection.', max_length=30),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='correction',
            field=models.TextField(blank=True, help_text='The immediate fix applied to the instance found.'),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='finding_type',
            field=models.CharField(choices=[('observation', 'Observation'), ('non_conformity', 'Non-Conformity'), ('major_non_conformity', 'Major Non-Conformity')], default='non_conformity', help_text='Observations record drift-risk practices without a breached requirement; non-conformities cite one.', max_length=30),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='requirement_reference',
            field=models.CharField(blank=True, help_text="The clause, standard, or manual section this finding fails, e.g. 'ISA 505' or 'Manual §4.2'.", max_length=255),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Evidence, recorded at a later date, that the corrective action held.'),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='corrective_action',
            field=models.TextField(blank=True, help_text='The action taken against the root cause.'),
        ),
    ]
