# Generated by Django 5.2.17 on 2026-10-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0002_nonconformance_category_nonconformance_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformance',
            name='management_response',
            field=models.TextField(blank=True, help_text="The audited entity's formal response to this finding, for inclusion in the management letter."),
        ),
    ]
