# Generated by Django 5.2.17 on 2026-09-04 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('engagement_type', models.CharField(choices=[('financial_statement', 'Financial Statement Audit'), ('compliance', 'Compliance Audit'), ('internal_control', 'Internal Controls Review'), ('it_audit', 'IT Audit'), ('other', 'Other')], default='financial_statement', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('risk_assessment', 'Risk Assessment'), ('fieldwork', 'Fieldwork'), ('reporting', 'Reporting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=30)),
                ('current_phase', models.CharField(choices=[('phase_1', 'Phase 1 - Planning'), ('phase_2', 'Phase 2 - Risk Assessment'), ('phase_3', 'Phase 3 - Risk Response'), ('phase_4', 'Phase 4 - Conclusion & Reporting'), ('completed', 'Completed')], default='phase_1', max_length=30)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('start_date', models.DateField()),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('financial_year_end', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='clients.client')),
                ('lead_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engagement',
                'verbose_name_plural': 'Engagements',
                'ordering': ['-created_at'],
            },
        ),
    ]
