# Generated by Django 5.2.17 on 2026-10-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='rolled_forward_from',
            field=models.ForeignKey(blank=True, help_text='The prior-period engagement this one was rolled forward from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_forward_engagements', to='engagements.engagement'),
        ),
    ]
