# Generated by Django 5.2.17 on 2026-10-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_engagement_rolled_forward_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='engagement_type',
            field=models.CharField(choices=[('financial_statement', 'Financial Statement Audit'), ('compliance', 'Compliance Audit'), ('internal_control', 'Internal Controls Review'), ('it_audit', 'IT Audit'), ('performance', 'Performance Audit'), ('forensic', 'Forensic Audit'), ('special', 'Special Audit'), ('environmental', 'Environmental Audit'), ('other', 'Other')], default='financial_statement', max_length=40),
        ),
    ]
