# Generated by Django 5.2.17 on 2026-10-09 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0002_engagement_rolled_forward_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('large_amount', 'Large posting above threshold'), ('round_number', 'Round-number amount'), ('off_hours', 'Weekend or off-hours posting'), ('backdated', 'Backdated transaction')], max_length=30)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Rule options, e.g. {"threshold": 1000000} for large_amount or {"max_age_days": 30} for backdated.')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monitoring_rules', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, help_text='Leave empty for a firm-wide (global) rule.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_rules', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Monitoring Rule',
                'verbose_name_plural': 'Monitoring Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('object_type', models.CharField(help_text='Model name of the triggering record.', max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Evidence captured from the triggering event.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_monitoring_alerts', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_alerts', to='engagements.engagement')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='monitoring.monitoringrule')),
            ],
            options={
                'verbose_name': 'Monitoring Alert',
                'verbose_name_plural': 'Monitoring Alerts',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['engagement', 'status'], name='monitoring__engagem_f246cb_idx'), models.Index(fields=['status', '-created_at'], name='monitoring__status_5254c8_idx')],
            },
        ),
    ]
