# Generated by Django 5.2.17 on 2026-09-07 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entities_in_scope', models.TextField(blank=True)),
                ('locations_in_scope', models.TextField(blank=True)),
                ('reporting_period', models.CharField(blank=True, max_length=100)),
                ('financial_statement_areas', models.TextField(blank=True)),
                ('significant_accounts', models.TextField(blank=True)),
                ('significant_disclosures', models.TextField(blank=True)),
                ('systems_in_scope', models.TextField(blank=True)),
                ('processes_in_scope', models.TextField(blank=True)),
                ('areas_out_of_scope', models.TextField(blank=True)),
                ('component_auditor_involvement', models.BooleanField(default=False)),
                ('component_auditor_details', models.TextField(blank=True)),
                ('scope_conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_scope', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmark', models.CharField(choices=[('revenue', 'Revenue'), ('profit_before_tax', 'Profit Before Tax'), ('total_assets', 'Total Assets'), ('equity', 'Equity'), ('expenses', 'Expenses'), ('other', 'Other')], default='profit_before_tax', max_length=30)),
                ('benchmark_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('benchmark_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('overall_materiality', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('performance_materiality', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('clearly_trivial_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rationale', models.TextField(blank=True)),
                ('qualitative_factors', models.TextField(blank=True)),
                ('reassessment_required', models.BooleanField(default=False)),
                ('reassessment_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materiality_assessment', to='engagements.engagement')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_materiality_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved')], default='not_started', max_length=20)),
                ('business_understanding', models.TextField(blank=True)),
                ('industry_understanding', models.TextField(blank=True)),
                ('regulatory_environment', models.TextField(blank=True)),
                ('accounting_framework', models.TextField(blank=True)),
                ('reporting_requirements', models.TextField(blank=True)),
                ('significant_changes', models.TextField(blank=True)),
                ('significant_risks_identified', models.TextField(blank=True)),
                ('fraud_risk_considerations', models.TextField(blank=True)),
                ('going_concern_considerations', models.TextField(blank=True)),
                ('related_parties_considerations', models.TextField(blank=True)),
                ('internal_audit_considerations', models.TextField(blank=True)),
                ('previous_auditor_considerations', models.TextField(blank=True)),
                ('planning_conclusion', models.TextField(blank=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_planning_assessments', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planning_assessment', to='engagements.engagement')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_planning_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter_type', models.CharField(choices=[('significant_risk', 'Significant Risk'), ('fraud', 'Fraud'), ('related_party', 'Related Party'), ('going_concern', 'Going Concern'), ('estimation', 'Accounting Estimation'), ('it', 'Information Technology'), ('regulatory', 'Regulatory'), ('litigation', 'Litigation'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('response_required', models.BooleanField(default=True)),
                ('planned_response', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_matters', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('engagement_partner', 'Engagement Partner'), ('engagement_manager', 'Engagement Manager'), ('senior_auditor', 'Senior Auditor'), ('auditor', 'Auditor'), ('assistant', 'Assistant'), ('it_specialist', 'IT Specialist'), ('tax_specialist', 'Tax Specialist'), ('valuation_specialist', 'Valuation Specialist'), ('other', 'Other')], max_length=30)),
                ('responsibilities', models.TextField(blank=True)),
                ('budgeted_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_key_member', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_team_members', to='engagements.engagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_team_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'user'), name='unique_engagement_team_member')],
            },
        ),
        migrations.CreateModel(
            name='PlanningProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField(blank=True)),
                ('procedure_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=20)),
                ('conclusion', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_procedures', to='engagements.engagement')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_planning_procedures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['procedure_code', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'procedure_code'), name='unique_planning_procedure_code')],
            },
        ),
    ]
