# Generated by Django 5.2.17 on 2026-09-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0001_initial'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFlowWalkthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255)),
                ('process_owner', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('walkthrough_date', models.DateField()),
                ('process_description', models.TextField(blank=True)),
                ('process_flow', models.TextField(blank=True)),
                ('key_controls', models.TextField(blank=True)),
                ('control_objectives', models.TextField(blank=True)),
                ('control_owner', models.CharField(blank=True, max_length=255)),
                ('it_applications', models.TextField(blank=True)),
                ('it_dependencies', models.TextField(blank=True)),
                ('interfaces', models.TextField(blank=True)),
                ('walkthrough_procedure', models.TextField(blank=True)),
                ('evidence_obtained', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('exceptions', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_flow_walkthrough', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Process Flow & Walkthrough',
                'verbose_name_plural': 'Process Flow & Walkthroughs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCycleAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_type', models.CharField(choices=[('revenue', 'Revenue'), ('purchasing_payables', 'Purchasing & Payables'), ('payroll', 'Payroll'), ('inventory', 'Inventory'), ('financial_statement_close', 'Financial Statement Close'), ('other_significant_processes', 'Other Significant Processes')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('significant_accounts', models.TextField(blank=True)),
                ('disclosure_processes', models.TextField(blank=True)),
                ('it_applications', models.TextField(blank=True)),
                ('it_dependencies', models.TextField(blank=True)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('not_assessed', 'Not Assessed'), ('assessed', 'Assessed')], default='not_assessed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_cycle_assessments', to='engagements.engagement')),
            ],
            options={
                'ordering': ['cycle_type', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'cycle_type'), name='unique_engagement_transaction_cycle')],
            },
        ),
    ]
