# Generated by Django 5.2.17 on 2026-09-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0002_processflowwalkthrough_transactioncycleassessment'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('account', models.CharField(max_length=255)),
                ('risk_description', models.TextField()),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('fraud_risk', models.BooleanField(default=False)),
                ('complexity', models.BooleanField(default=False)),
                ('subjectivity', models.BooleanField(default=False)),
                ('uncertainty', models.BooleanField(default=False)),
                ('management_bias', models.BooleanField(default=False)),
                ('likelihood', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Significant', 'Significant')], default='Medium', max_length=20)),
                ('magnitude', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Significant', 'Significant')], default='Medium', max_length=20)),
                ('significant_risk', models.BooleanField(default=False)),
                ('control_response', models.TextField(blank=True)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_points', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Risk Point',
                'verbose_name_plural': 'Risk Points',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
