# Generated by Django 5.2.17 on 2026-09-09 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0003_riskpoint'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('control_id', models.CharField(max_length=100)),
                ('process_cycle', models.CharField(max_length=255)),
                ('control_objective', models.TextField()),
                ('control_description', models.TextField()),
                ('control_type', models.CharField(choices=[('Preventive', 'Preventive'), ('Detective', 'Detective')], default='Preventive', max_length=20)),
                ('control_nature', models.CharField(choices=[('Manual', 'Manual'), ('IT Dependent Manual', 'IT Dependent Manual'), ('Automated', 'Automated')], default='Manual', max_length=30)),
                ('frequency', models.CharField(choices=[('Continuous', 'Continuous'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually'), ('As Needed', 'As Needed')], default='Daily', max_length=30)),
                ('control_owner', models.CharField(max_length=255)),
                ('control_evidence', models.TextField(blank=True)),
                ('key_control', models.BooleanField(default=False)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('reliance_planned', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('To Be Determined', 'To Be Determined')], default='To Be Determined', max_length=30)),
                ('design_effectiveness', models.CharField(choices=[('Effective', 'Effective'), ('Partially Effective', 'Partially Effective'), ('Ineffective', 'Ineffective'), ('Not Assessed', 'Not Assessed')], default='Not Assessed', max_length=30)),
                ('control_deficiencies', models.TextField(blank=True)),
                ('auditor_conclusion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Controls',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
