# Generated by Django 5.2.17 on 2026-09-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0004_control'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.CharField(max_length=255)),
                ('control_reference', models.CharField(max_length=100)),
                ('assertion', models.CharField(choices=[('Existence', 'Existence'), ('Completeness', 'Completeness'), ('Accuracy', 'Accuracy'), ('Cut-off', 'Cut-off'), ('Occurrence', 'Occurrence'), ('Classification', 'Classification'), ('Valuation', 'Valuation'), ('Rights & Obligations', 'Rights & Obligations'), ('Presentation & Disclosure', 'Presentation & Disclosure')], max_length=50)),
                ('control_type', models.CharField(choices=[('Manual', 'Manual'), ('IT Dependent Manual', 'IT Dependent Manual'), ('Automated', 'Automated'), ('IT General Control', 'IT General Control')], max_length=50)),
                ('testing_objective', models.TextField(blank=True)),
                ('test_procedure', models.TextField(blank=True)),
                ('population', models.TextField(blank=True)),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True)),
                ('sampling_method', models.CharField(blank=True, choices=[('Random', 'Random'), ('Systematic', 'Systematic'), ('Judgmental', 'Judgmental'), ('Stratified', 'Stratified'), ('Full Population', 'Full Population')], max_length=30)),
                ('audit_evidence', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('Not Started', 'Not Started'), ('Passed', 'Passed'), ('Exception', 'Exception'), ('Failed', 'Failed'), ('Not Applicable', 'Not Applicable')], default='Not Started', max_length=30)),
                ('exceptions_found', models.PositiveIntegerField(default=0)),
                ('exception_nature', models.TextField(blank=True)),
                ('exception_effect', models.TextField(blank=True)),
                ('reliance_decision', models.CharField(blank=True, choices=[('Rely in Full', 'Rely in Full'), ('Rely in Part', 'Rely in Part'), ('Do Not Rely', 'Do Not Rely'), ('Substantive Approach Required', 'Substantive Approach Required')], max_length=50)),
                ('auditor_conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_test_executions', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Control Test Execution',
                'verbose_name_plural': 'Control Test Executions',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
