# Generated by Django 5.2.17 on 2026-09-09 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0005_controltestexecution'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterimYearEndAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.CharField(max_length=255)),
                ('interim_date', models.DateField()),
                ('year_end_date', models.DateField()),
                ('interim_testing', models.TextField(blank=True)),
                ('control_changes', models.TextField(blank=True)),
                ('remaining_period', models.TextField(blank=True)),
                ('additional_testing', models.TextField(blank=True)),
                ('exceptions', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interim_year_end_assessments', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Interim Year-End Assessment',
                'verbose_name_plural': 'Interim Year-End Assessments',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
