# Generated by Django 5.2.17 on 2026-09-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0006_interimyearendassessment'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudJournalEntryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_description', models.TextField(blank=True)),
                ('population_period', models.CharField(blank=True, max_length=255)),
                ('total_population', models.PositiveIntegerField(blank=True, null=True)),
                ('selection_method', models.CharField(blank=True, choices=[('Risk-based', 'Risk-based'), ('Random', 'Random'), ('Full Population', 'Full Population'), ('Data Analytics', 'Data Analytics'), ('Judgmental', 'Judgmental')], max_length=30)),
                ('selected_entries', models.PositiveIntegerField(blank=True, null=True)),
                ('selection_rationale', models.TextField(blank=True)),
                ('journal_entry_testing', models.TextField(blank=True)),
                ('testing_period', models.CharField(blank=True, max_length=255)),
                ('journal_entry_criteria', models.TextField(blank=True)),
                ('journal_entry_evidence', models.TextField(blank=True)),
                ('management_override_procedures', models.TextField(blank=True)),
                ('override_results', models.TextField(blank=True)),
                ('data_analytics_anomalies', models.TextField(blank=True)),
                ('anomaly_analysis', models.TextField(blank=True)),
                ('possible_fraud_indicators', models.TextField(blank=True)),
                ('fraud_risk_assessment', models.TextField(blank=True)),
                ('exceptions', models.TextField(blank=True)),
                ('exceptions_count', models.PositiveIntegerField(default=0)),
                ('exception_resolution', models.TextField(blank=True)),
                ('auditor_conclusion', models.TextField(blank=True)),
                ('fraud_implication', models.TextField(blank=True)),
                ('further_procedures_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_journal_entry_assessments', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Fraud Journal Entry Assessment',
                'verbose_name_plural': 'Fraud Journal Entry Assessments',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
