# Generated by Django 5.2.17 on 2026-09-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0007_fraudjournalentryassessment'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstantiveProcedureAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(blank=True, max_length=255)),
                ('procedure_type', models.CharField(choices=[('Analytical Procedures', 'Analytical Procedures'), ('Key Item Testing', 'Key Item Testing'), ('Sampling', 'Sampling'), ('Confirmation', 'Confirmation'), ('Full Population Analytics', 'Full Population Analytics'), ('Inventory Attendance', 'Inventory Attendance'), ('Legal Letter', 'Legal Letter'), ('Segment Testing', 'Segment Testing')], max_length=50)),
                ('financial_statement_area', models.CharField(blank=True, max_length=255)),
                ('account_balance', models.CharField(blank=True, max_length=255)),
                ('assertion', models.CharField(blank=True, max_length=100)),
                ('procedure_objective', models.TextField(blank=True)),
                ('population_description', models.TextField(blank=True)),
                ('population_period', models.CharField(blank=True, max_length=255)),
                ('population_size', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_size', models.PositiveIntegerField(blank=True, null=True)),
                ('sampling_method', models.CharField(blank=True, max_length=255)),
                ('selection_rationale', models.TextField(blank=True)),
                ('procedure_performed', models.TextField(blank=True)),
                ('testing_results', models.TextField(blank=True)),
                ('evidence_obtained', models.TextField(blank=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('exceptions_misstatements', models.TextField(blank=True)),
                ('exceptions_count', models.PositiveIntegerField(default=0)),
                ('misstatement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('exception_resolution', models.TextField(blank=True)),
                ('auditor_conclusion', models.TextField(blank=True)),
                ('further_procedures_required', models.BooleanField(default=False)),
                ('further_procedures_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substantive_procedure_assessments', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Substantive Procedure Assessment',
                'verbose_name_plural': 'Substantive Procedure Assessments',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
