# Generated by Django 5.2.17 on 2026-09-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0008_substantiveprocedureassessment'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAuditProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_type', models.CharField(choices=[('Group Audit', 'Group Audit'), ('Internal Audit Reliance', 'Internal Audit Reliance'), ('Expert Involvement', 'Expert Involvement'), ('Sampling', 'Sampling'), ('Accounting Estimates', 'Accounting Estimates'), ('Financial Statement Close Process', 'Financial Statement Close Process'), ('Sustainability', 'Sustainability'), ('Service Organization', 'Service Organization'), ('Complex Transactions', 'Complex Transactions')], max_length=100)),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('procedure_performed', models.TextField(blank=True)),
                ('evidence_documentation', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('issues_follow_up', models.TextField(blank=True)),
                ('auditor_conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_audit_procedures', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'General Audit Procedure',
                'verbose_name_plural': 'General Audit Procedures',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
