# Generated by Django 5.2.17 on 2026-09-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0009_generalauditprocedure'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReassessedCombinedRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_area', models.CharField(max_length=255)),
                ('assertion', models.CharField(choices=[('Occurrence', 'Occurrence'), ('Completeness', 'Completeness'), ('Accuracy', 'Accuracy'), ('Cut-off', 'Cut-off'), ('Existence', 'Existence'), ('Valuation', 'Valuation'), ('Rights & Obligations', 'Rights & Obligations'), ('Classification', 'Classification'), ('Presentation & Disclosure', 'Presentation & Disclosure')], max_length=100)),
                ('original_risk_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Significant', 'Significant')], max_length=20)),
                ('new_audit_evidence', models.TextField(blank=True)),
                ('unexpected_results', models.TextField(blank=True)),
                ('control_exceptions', models.TextField(blank=True)),
                ('misstatements_identified', models.TextField(blank=True)),
                ('confirmation_exceptions', models.TextField(blank=True)),
                ('reassessed_risk_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Significant', 'Significant')], max_length=20)),
                ('reason_for_risk_change', models.TextField(blank=True)),
                ('additional_audit_procedures', models.TextField(blank=True)),
                ('auditor_conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassessed_combined_risks', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Reassessed Combined Risk',
                'verbose_name_plural': 'Reassessed Combined Risks',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
