# Generated by Django 5.2.17 on 2026-09-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0010_reassessedcombinedrisk'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisstatementAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('financial_statement_area', models.CharField(blank=True, max_length=255)),
                ('account', models.CharField(blank=True, max_length=255)),
                ('assertion', models.CharField(choices=[('Occurrence', 'Occurrence'), ('Completeness', 'Completeness'), ('Accuracy', 'Accuracy'), ('Cut-off', 'Cut-off'), ('Existence', 'Existence'), ('Valuation', 'Valuation'), ('Rights & Obligations', 'Rights & Obligations'), ('Classification', 'Classification'), ('Presentation & Disclosure', 'Presentation & Disclosure')], max_length=100)),
                ('nature', models.CharField(choices=[('Factual', 'Factual'), ('Judgmental', 'Judgmental'), ('Projected', 'Projected')], max_length=30)),
                ('identified_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('projected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('aggregated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('correction_status', models.CharField(choices=[('Corrected', 'Corrected'), ('Uncorrected', 'Uncorrected'), ('Partially Corrected', 'Partially Corrected')], default='Uncorrected', max_length=30)),
                ('management_response', models.TextField(blank=True)),
                ('materiality_reference', models.TextField(blank=True)),
                ('evaluation_result', models.CharField(blank=True, choices=[('Clearly Trivial', 'Clearly Trivial'), ('Below Materiality', 'Below Materiality'), ('Material', 'Material'), ('Qualitatively Material', 'Qualitatively Material'), ('Potentially Material', 'Potentially Material')], max_length=40)),
                ('qualitative_factors', models.TextField(blank=True)),
                ('financial_statement_effect', models.TextField(blank=True)),
                ('included_in_uncorrected_summary', models.BooleanField(default=False)),
                ('communicated_to_management', models.BooleanField(default=False)),
                ('communicated_to_governance', models.BooleanField(default=False)),
                ('written_representation_required', models.BooleanField(default=False)),
                ('written_representation_obtained', models.BooleanField(default=False)),
                ('further_procedures_required', models.BooleanField(default=False)),
                ('further_procedures_description', models.TextField(blank=True)),
                ('effect_on_audit_opinion', models.TextField(blank=True)),
                ('auditor_conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misstatement_assessments', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Misstatement Assessment',
                'verbose_name_plural': 'Misstatement Assessments',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MisstatementEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_materiality', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('performance_materiality', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('clearly_trivial_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_identified_misstatements', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_corrected_misstatements', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_uncorrected_misstatements', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('aggregate_effect', models.TextField(blank=True)),
                ('qualitative_factors', models.TextField(blank=True)),
                ('management_response', models.TextField(blank=True)),
                ('governance_communication', models.TextField(blank=True)),
                ('written_representation_considered', models.BooleanField(default=False)),
                ('written_representation_obtained', models.BooleanField(default=False)),
                ('effect_on_audit_opinion', models.TextField(blank=True)),
                ('further_procedures_required', models.BooleanField(default=False)),
                ('further_procedures_description', models.TextField(blank=True)),
                ('overall_conclusion', models.CharField(blank=True, choices=[('No Material Misstatements', 'No Material Misstatements'), ('Misstatements Corrected', 'Misstatements Corrected'), ('Uncorrected Misstatements Not Material', 'Uncorrected Misstatements Not Material'), ('Material Uncorrected Misstatements', 'Material Uncorrected Misstatements'), ('Further Evaluation Required', 'Further Evaluation Required')], max_length=60)),
                ('auditor_conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='misstatement_evaluation', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Misstatement Evaluation',
                'verbose_name_plural': 'Misstatement Evaluations',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
