# Generated by Django 5.2.17 on 2026-09-10 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0011_misstatementassessment_misstatementevaluation'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20)),
                ('inspection_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Applicable', 'Not Applicable')], default='Not Started', max_length=20)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('inspector_name', models.CharField(blank=True, max_length=255)),
                ('monitoring_period', models.CharField(blank=True, max_length=255)),
                ('next_monitoring_date', models.DateField(blank=True, null=True)),
                ('inspection_scope', models.TextField(blank=True)),
                ('inspection_methodology', models.TextField(blank=True)),
                ('inspection_conclusion', models.TextField(blank=True)),
                ('firm_methodology_feedback', models.TextField(blank=True)),
                ('training_feedback', models.TextField(blank=True)),
                ('staffing_feedback', models.TextField(blank=True)),
                ('supervision_feedback', models.TextField(blank=True)),
                ('engagement_performance_conclusion', models.TextField(blank=True)),
                ('overall_quality_conclusion', models.TextField(blank=True)),
                ('leadership_review_completed', models.BooleanField(default=False)),
                ('findings_communicated', models.BooleanField(default=False)),
                ('root_cause_completed', models.BooleanField(default=False)),
                ('remediation_plan_approved', models.BooleanField(default=False)),
                ('effectiveness_monitoring_completed', models.BooleanField(default=False)),
                ('quality_leadership_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_monitoring', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Quality Monitoring',
                'verbose_name_plural': 'Quality Monitoring',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('Significant', 'Significant'), ('Severe', 'Severe')], default='Moderate', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Remediated', 'Remediated'), ('Accepted', 'Accepted'), ('Not Applicable', 'Not Applicable')], default='Open', max_length=30)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quality_monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit_planning.qualitymonitoring')),
            ],
            options={
                'verbose_name': 'Quality Finding',
                'verbose_name_plural': 'Quality Findings',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RemediationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('action', models.TextField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Monitoring', 'Monitoring')], default='Not Started', max_length=20)),
                ('effectiveness', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quality_monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_actions', to='audit_planning.qualitymonitoring')),
            ],
            options={
                'verbose_name': 'Remediation Action',
                'verbose_name_plural': 'Remediation Actions',
                'ordering': ['id'],
            },
        ),
    ]
