# Generated by Django 5.2.17 on 2026-09-24 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0012_qualitymonitoring_qualityfinding_remediationaction'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('retention_period_years', models.PositiveIntegerField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_status', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Archive Status',
                'verbose_name_plural': 'Archive Statuses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_archive', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Documentation Archive',
                'verbose_name_plural': 'Documentation Archives',
                'ordering': ['-updated_at'],
            },
        ),
    ]
