# Generated by Django 5.2.17 on 2026-09-16 11:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('financial_statement_section', models.CharField(blank=True, choices=[('statement_of_financial_position', 'Statement of Financial Position'), ('profit_or_loss', 'Profit or Loss'), ('cash_flow', 'Cash Flow Statement'), ('equity', 'Statement of Changes in Equity'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='engagements.engagement')),
            ],
            options={
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('imported', 'Imported'), ('reviewed', 'Reviewed'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balances', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrialBalanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_balance_lines', to='financials.chartofaccount')),
                ('trial_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='financials.trialbalance')),
            ],
            options={
                'ordering': ['account_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(fields=('engagement', 'account_code'), name='unique_account_code_per_engagement'),
        ),
        migrations.AddConstraint(
            model_name='trialbalanceline',
            constraint=models.UniqueConstraint(fields=('trial_balance', 'account'), name='unique_account_per_trial_balance'),
        ),
    ]
