# Generated by Django 5.2.17 on 2026-09-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='trial_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='financials.trialbalance'),
        ),
    ]
