# Generated by Django 5.2.17 on 2026-09-18 07:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('financials', '0003_adjustment_trial_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('purpose', models.TextField(blank=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('adjusted_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('auditor_notes', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_schedules', to='financials.chartofaccount')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_schedules', to='engagements.engagement')),
                ('trial_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_schedules', to='financials.trialbalance')),
            ],
            options={
                'ordering': ['schedule_name'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'trial_balance', 'account'), name='unique_lead_schedule_per_tb_account')],
            },
        ),
    ]
