# Generated by Django 5.2.17 on 2026-09-21 05:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_leadschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('audit_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('tested', 'Tested'), ('agreed', 'Agreed'), ('exception', 'Exception')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_details', to='financials.leadschedule')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
