# Generated by Django 5.2.17 on 2026-09-29 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('financials', '0005_supportingdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('trial_balance', 'Trial Balance'), ('adjustment', 'Adjustment'), ('other', 'Other')], default='manual', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_ledger_entries', to='financials.chartofaccount')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_entries', to='engagements.engagement')),
            ],
            options={
                'ordering': ['transaction_date', 'id'],
                'indexes': [models.Index(fields=['engagement', 'transaction_date'], name='financials__engagem_f1eff4_idx'), models.Index(fields=['account', 'transaction_date'], name='financials__account_ddb999_idx'), models.Index(fields=['status'], name='financials__status_e84ad7_idx')],
            },
        ),
    ]
