# Generated by Django 5.2.17 on 2026-09-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_journalentry_journalline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('trial_balance', 'Trial Balance'), ('adjustment', 'Adjustment'), ('journal', 'Journal'), ('other', 'Other')], default='manual', max_length=30),
        ),
    ]
