# Generated by Django 5.2.17 on 2026-10-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('financials', '0009_bankstatement_financialbudget_financialbudgetline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_type', models.CharField(choices=[('class', 'Class'), ('location', 'Location'), ('project', 'Project')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['dimension_type', 'name', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='financialbudgetline',
            name='unique_budget_account_month',
        ),
        migrations.AddField(
            model_name='financialbudgetline',
            name='dimension_signature',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='financialdimension',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_dimensions', to='engagements.engagement'),
        ),
        migrations.AddField(
            model_name='financialbudgetline',
            name='dimensions',
            field=models.ManyToManyField(blank=True, related_name='budget_lines', to='financials.financialdimension'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='dimensions',
            field=models.ManyToManyField(blank=True, related_name='ledger_entries', to='financials.financialdimension'),
        ),
        migrations.AddConstraint(
            model_name='financialbudgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'account', 'period', 'dimension_signature'), name='unique_budget_account_month'),
        ),
        migrations.AddConstraint(
            model_name='financialdimension',
            constraint=models.UniqueConstraint(fields=('engagement', 'dimension_type', 'name'), name='unique_financial_dimension_name'),
        ),
    ]
