# Generated by Django 5.2.17 on 2026-10-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_financialdimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='dimensions',
            field=models.ManyToManyField(blank=True, related_name='journal_lines', to='financials.financialdimension'),
        ),
    ]
