# Generated by Django 5.2.17 on 2026-10-06 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('financials', '0012_generalledger_journal_line_journalentry_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingpolicy',
            name='base_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.CreateModel(
            name='FinancialContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagements.engagement')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invoice', 'Sales Invoice'), ('bill', 'Supplier Bill'), ('sales_credit', 'Sales Credit Note'), ('purchase_credit', 'Purchase Credit Note')], max_length=20)),
                ('number', models.CharField(max_length=50)),
                ('transaction_date', models.DateField()),
                ('due_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.financialcontact')),
                ('control_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.chartofaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagements.engagement')),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_document', to='financials.journalentry')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='financials.financialdocument')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('control_base_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fx_difference', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_payments', to='financials.chartofaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='financials.financialdocument')),
                ('fx_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_fx_payments', to='financials.chartofaccount')),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_payment', to='financials.journalentry')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagements.engagement')),
                ('purchase_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_tax_codes', to='financials.chartofaccount')),
                ('sales_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_tax_codes', to='financials.chartofaccount')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('base_net', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('base_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financials.chartofaccount')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='financials.financialdocument')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financials.financialtaxcode')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='financialcontact',
            constraint=models.UniqueConstraint(fields=('engagement', 'kind', 'name'), name='unique_financial_contact'),
        ),
        migrations.AddConstraint(
            model_name='financialdocument',
            constraint=models.UniqueConstraint(fields=('engagement', 'kind', 'number'), name='unique_financial_document_number'),
        ),
        migrations.AddConstraint(
            model_name='financialdocument',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='financial_document_positive_rate'),
        ),
        migrations.AddConstraint(
            model_name='financialpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='financial_payment_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='financialpayment',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='financial_payment_positive_rate'),
        ),
        migrations.AddConstraint(
            model_name='financialtaxcode',
            constraint=models.UniqueConstraint(fields=('engagement', 'name'), name='unique_financial_tax_code'),
        ),
        migrations.AddConstraint(
            model_name='financialtaxcode',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='financial_tax_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='financialdocumentline',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gt', 0)), name='financial_document_positive_net'),
        ),
    ]
