# Generated by Django 5.2.17 on 2026-10-06 05:44

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('financials', '0013_accountingpolicy_base_currency_financialcontact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('registration_mode', models.CharField(choices=[('new', 'New acquisition'), ('existing', 'Already recorded in ledger')], max_length=10)),
                ('acquisition_date', models.DateField()),
                ('depreciation_start', models.DateField()),
                ('depreciation_months', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('opening_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accumulated_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accumulated_assets', to='financials.chartofaccount')),
                ('acquisition_journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset', to='financials.journalentry')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='financials.chartofaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagements.engagement')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_assets', to='financials.chartofaccount')),
                ('funding_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funded_assets', to='financials.chartofaccount')),
            ],
            options={
                'ordering': ['asset_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FixedAssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('depreciation', 'Monthly depreciation'), ('disposal', 'Disposal')], max_length=15)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='financials.fixedasset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_event', to='financials.journalentry')),
            ],
            options={
                'ordering': ['transaction_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.UniqueConstraint(fields=('engagement', 'asset_number'), name='unique_fixed_asset_number'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gt', 0)), name='fixed_asset_positive_cost'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.CheckConstraint(condition=models.Q(('opening_depreciation__gte', 0), ('residual_value__gte', 0), ('cost__gte', django.db.models.expressions.CombinedExpression(models.F('residual_value'), '+', models.F('opening_depreciation')))), name='fixed_asset_value_range'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.CheckConstraint(condition=models.Q(('depreciation_months__gte', 1), ('depreciation_months__lte', 1200)), name='fixed_asset_months_range'),
        ),
        migrations.AddConstraint(
            model_name='fixedassetevent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='fixed_asset_event_nonnegative'),
        ),
    ]
