# Generated by Django 5.2.17 on 2026-10-06 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('financials', '0014_fixedasset_fixedassetevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagements.engagement')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_expense_items', to='financials.chartofaccount')),
                ('inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='financials.chartofaccount')),
            ],
            options={
                'ordering': ['sku', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opening', 'Opening stock'), ('receipt', 'Stock receipt'), ('issue', 'Stock issue'), ('increase', 'Positive stock adjustment'), ('decrease', 'Negative stock adjustment')], max_length=10)),
                ('transaction_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('quantity_before', models.DecimalField(decimal_places=4, max_digits=18)),
                ('quantity_after', models.DecimalField(decimal_places=4, max_digits=18)),
                ('value_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('value_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(max_length=500)),
                ('register_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='financials.inventoryitem')),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movement', to='financials.journalentry')),
                ('offset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financials.chartofaccount')),
            ],
            options={
                'ordering': ['transaction_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('engagement', 'sku'), name='unique_inventory_sku'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('value__gt', 0)), name='inventory_positive_movement'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_after__gte', 0), ('quantity_before__gte', 0), ('value_after__gte', 0), ('value_before__gte', 0)), name='inventory_nonnegative_balances'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('journal__isnull', True), ('kind', 'opening'), ('offset_account__isnull', True), ('register_only', True)), models.Q(('journal__isnull', False), ('offset_account__isnull', False), ('register_only', False)), _connector='OR'), name='inventory_movement_source'),
        ),
    ]
