# Generated by Django 5.2.17 on 2026-10-06 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('financials', '0015_inventoryitem_inventorymovement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIntelligenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('algorithm_version', models.CharField(max_length=30)),
                ('parameters', models.JSONField()),
                ('population_fingerprint', models.CharField(max_length=64)),
                ('population_count', models.PositiveIntegerField()),
                ('sample_count', models.PositiveIntegerField()),
                ('finding_count', models.PositiveIntegerField()),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engagements.engagement')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
