# Generated by Django 5.2.17 on 2026-10-06 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('financials', '0016_financialintelligencerun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('filename', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=80)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('content', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engagements.engagement')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(choices=[('account_trace', 'Trial balance account trace'), ('run', 'Audit intelligence run'), ('run_finding', 'Saved run finding'), ('ledger', 'Ledger entry'), ('journal', 'Journal entry'), ('adjustment', 'Audit adjustment'), ('lead_schedule', 'Lead schedule'), ('supporting_detail', 'Supporting detail'), ('document', 'Invoice, bill or credit'), ('payment', 'Document payment'), ('asset', 'Fixed asset'), ('asset_event', 'Asset event'), ('inventory_item', 'Stock item'), ('inventory_movement', 'Stock movement')], max_length=30)),
                ('target_id', models.PositiveBigIntegerField()),
                ('selector', models.BigIntegerField(default=-1)),
                ('target_snapshot', models.JSONField()),
                ('note', models.CharField(max_length=1000)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='financials.financialevidence')),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-linked_at', '-id'],
                'indexes': [models.Index(fields=['target_kind', 'target_id', 'selector'], name='financials__target__9ef129_idx')],
                'constraints': [models.UniqueConstraint(fields=('evidence', 'target_kind', 'target_id', 'selector'), name='unique_financial_evidence_target')],
            },
        ),
    ]
