# Generated by Django 5.2.17 on 2026-10-06 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0017_financialevidence_financialevidencelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFindingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_index', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('review', 'Record review outcome'), ('sign_off', 'Independent sign-off'), ('return', 'Return for further work'), ('reopen', 'Reopen signed-off finding')], max_length=20)),
                ('outcome', models.CharField(choices=[('explained', 'Explained / no exception identified'), ('exception', 'Exception confirmed'), ('follow_up', 'Further work required')], max_length=20)),
                ('conclusion', models.TextField()),
                ('note', models.TextField()),
                ('evidence_link_ids', models.JSONField(default=list)),
                ('actor_identifier', models.PositiveBigIntegerField()),
                ('actor_name', models.CharField(max_length=150)),
                ('actor_role', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='financials.financialfindingreview')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finding_reviews', to='financials.financialintelligencerun')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['run', 'finding_index', '-id'], name='financials__run_id_b67e98_idx')],
            },
        ),
    ]
