# Generated by Django 5.2.17 on 2026-10-06 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('financials', '0018_financialfindingreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialevidencelink',
            name='target_kind',
            field=models.CharField(choices=[('account_trace', 'Trial balance account trace'), ('run', 'Audit intelligence run'), ('run_finding', 'Saved run finding'), ('ledger', 'Ledger entry'), ('journal', 'Journal entry'), ('adjustment', 'Audit adjustment'), ('lead_schedule', 'Lead schedule'), ('supporting_detail', 'Supporting detail'), ('document', 'Invoice, bill or credit'), ('payment', 'Document payment'), ('asset', 'Fixed asset'), ('asset_event', 'Asset event'), ('inventory_item', 'Stock item'), ('inventory_movement', 'Stock movement'), ('pbc_request', 'PBC document request')], max_length=30),
        ),
        migrations.CreateModel(
            name='FinancialPBCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requested_from', models.CharField(max_length=200)),
                ('responsible_name', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engagements.engagement')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPBCEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submit documents'), ('accept', 'Accept submission'), ('return', 'Return for further documents'), ('reopen', 'Reopen accepted request'), ('cancel', 'Cancel request')], max_length=10)),
                ('note', models.TextField()),
                ('evidence_link_ids', models.JSONField(default=list)),
                ('actor_identifier', models.PositiveBigIntegerField()),
                ('actor_name', models.CharField(max_length=150)),
                ('actor_role', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='financials.financialpbcevent')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='financials.financialpbcrequest')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['request', '-id'], name='financials__request_8e3358_idx')],
            },
        ),
    ]
