# Generated by Django 5.2.17 on 2026-10-06 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('financials', '0019_alter_financialevidencelink_target_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('group', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('note_reference', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engagements.engagement')),
            ],
            options={
                'ordering': ['order', 'code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialStatementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='statement_mapping', to='financials.chartofaccount')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='financials.financialstatementline')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('current_tb_id', models.PositiveBigIntegerField()),
                ('comparison_tb_id', models.PositiveBigIntegerField(null=True)),
                ('results', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('preparer_identifier', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engagements.engagement')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialStatementApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_identifier', models.PositiveBigIntegerField()),
                ('actor_name', models.CharField(max_length=150)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval', to='financials.financialstatementversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='financialstatementline',
            constraint=models.UniqueConstraint(fields=('engagement', 'code'), name='unique_statement_line_code'),
        ),
    ]
