# Generated by Django 5.2.17 on 2026-10-08 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('financials', '0020_financialstatementline_financialstatementmapping_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=100)),
                ('external_code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_mappings', to='financials.chartofaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagements.engagement')),
            ],
            options={
                'ordering': ['source_system', 'external_code'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'source_system', 'external_code'), name='unique_financial_account_import_mapping')],
            },
        ),
        migrations.CreateModel(
            name='FinancialDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=255)),
                ('source_format', models.CharField(max_length=10)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(max_length=10)),
                ('column_mapping', models.JSONField(default=dict)),
                ('rows', models.JSONField(default=list)),
                ('validation_errors', models.JSONField(default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
                ('status', models.CharField(choices=[('needs_review', 'Needs review'), ('validated', 'Validated'), ('imported', 'Imported')], default='needs_review', max_length=20)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engagements.engagement')),
                ('trial_balance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_import', to='financials.trialbalance')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['engagement', 'created_at'], name='financials__engagem_8ec164_idx'), models.Index(fields=['source_fingerprint'], name='financials__source__36b3b6_idx')],
            },
        ),
    ]
