# Generated by Django 5.2.17 on 2026-10-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0021_financialaccountmapping_financialdataimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='is_memorandum',
            field=models.BooleanField(default=False, help_text='Memorandum entries are recorded for disclosure or informational purposes and are excluded from the adjusted trial balance even when posted.'),
        ),
    ]
