# Generated by Django 5.2.17 on 2026-10-09 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_license_authority_client_license_expiry_date'),
        ('engagements', '0002_engagement_rolled_forward_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated, e.g. AR-000042.', max_length=30, unique=True)),
                ('company_name', models.CharField(help_text='Company name as stated by the requester.', max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('audit_type', models.CharField(choices=[('financial_statement', 'Financial Statement Audit'), ('compliance', 'Compliance Audit'), ('internal_control', 'Internal Controls Review'), ('it_audit', 'IT Audit'), ('other', 'Other')], default='financial_statement', max_length=40)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('preferred_end_date', models.DateField(blank=True, null=True)),
                ('scope_notes', models.TextField(blank=True, help_text='Scope, locations, periods, or special requirements.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('converted', 'Converted to Engagement')], default='submitted', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Existing client, when the requester is known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_requests', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_audit_requests', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(blank=True, help_text='Engagement created when this request was converted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_requests', to='engagements.engagement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_audit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Request',
                'verbose_name_plural': 'Audit Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
