# Generated by Django 5.2.17 on 2026-09-22 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
        ('review_workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgments', models.JSONField(blank=True, default=list)),
                ('uncorrected_misstatements', models.JSONField(blank=True, default=dict)),
                ('financial_statement_confirmations', models.JSONField(blank=True, default=dict)),
                ('engagement_team_review', models.JSONField(blank=True, default=dict)),
                ('partner_review', models.JSONField(blank=True, default=dict)),
                ('eqr_review', models.JSONField(blank=True, default=dict)),
                ('review_comments', models.JSONField(blank=True, default=list)),
                ('overall_conclusion', models.TextField(blank=True)),
                ('approval_comments', models.TextField(blank=True)),
                ('completion_checklist', models.JSONField(blank=True, default=dict)),
                ('completion_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_review', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
