# Generated by Django 5.2.17 on 2026-10-09 06:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, default='General', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist Template',
                'verbose_name_plural': 'Checklist Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.TextField()),
                ('response_type', models.CharField(choices=[('yes_no', 'Yes / No'), ('yes_no_na', 'Yes / No / N/A'), ('text', 'Text'), ('number', 'Number'), ('rating', 'Rating (1-5)')], default='yes_no_na', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Scoring weight for this question.', max_digits=8)),
                ('condition_value', models.CharField(blank=True, help_text="Show this sub-question only when the parent answer equals this value (e.g. 'no').", max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='checklists.checklistitem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Checklist Item',
                'verbose_name_plural': 'Checklist Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EngagementChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_engagement_checklists', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='engagements.engagement')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagement_checklists', to='checklists.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Engagement Checklist',
                'verbose_name_plural': 'Engagement Checklists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text='yes / no / na for yes-no questions.', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 for rating questions.', null=True)),
                ('text_value', models.TextField(blank=True, help_text='Answer for text/number questions.')),
                ('comment', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.checklistitem')),
                ('engagement_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.engagementchecklist')),
            ],
            options={
                'verbose_name': 'Checklist Response',
                'verbose_name_plural': 'Checklist Responses',
                'ordering': ['item__order', 'item__id'],
                'unique_together': {('engagement_checklist', 'item')},
            },
        ),
    ]
