# Generated by Django 5.2.17 on 2026-10-09 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated, e.g. FR-000042.', max_length=30, unique=True)),
                ('subject', models.CharField(help_text='Entity, person, or area the report concerns.', max_length=255)),
                ('description', models.TextField(help_text='What happened, where, when, and who is involved.')),
                ('reporter_name', models.CharField(blank=True, help_text='Optional — anonymous reports are accepted.', max_length=255)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('investigating', 'Investigating'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('triage_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Report',
                'verbose_name_plural': 'Fraud Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
