# Generated by Django 5.2.17 on 2026-09-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=50, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('client_type', models.CharField(choices=[('company', 'Company'), ('government', 'Government'), ('ngo', 'NGO'), ('bank', 'Bank'), ('insurance', 'Insurance'), ('other', 'Other')], default='company', max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_identification_number', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('inactive', 'Inactive')], default='prospect', max_length=30)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['legal_name'],
            },
        ),
    ]
