# Generated by Django 5.2.17 on 2026-10-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='license_authority',
            field=models.CharField(blank=True, help_text='Authority that issued the trade/practice license.', max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
