# Generated by Django 5.2.17 on 2026-10-09 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0002_engagement_rolled_forward_from'),
        ('financials', '0022_adjustment_is_memorandum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('random', 'Random'), ('systematic', 'Systematic'), ('mus', 'Monetary-Unit Sampling')], max_length=20)),
                ('population_size', models.PositiveIntegerField()),
                ('population_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sample_size', models.PositiveIntegerField()),
                ('seed', models.BigIntegerField(help_text='Random seed — reproduce the selection.')),
                ('interval', models.DecimalField(blank=True, decimal_places=2, help_text='Sampling interval (systematic and MUS).', max_digits=20, null=True)),
                ('items', models.JSONField(default=list, help_text='Selected population items with identifiers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, help_text='Population restricted to this account, if set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_selections', to='financials.chartofaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_samples', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_selections', to='engagements.engagement')),
            ],
            options={
                'verbose_name': 'Sample Selection',
                'verbose_name_plural': 'Sample Selections',
                'ordering': ['-created_at'],
            },
        ),
    ]
