# Generated by Django 5.2.17 on 2026-09-11 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=30)),
                ('financial_statements_finalized', models.BooleanField(default=False)),
                ('audit_adjustments_reviewed', models.BooleanField(default=False)),
                ('subsequent_events_reviewed', models.BooleanField(default=False)),
                ('going_concern_reviewed', models.BooleanField(default=False)),
                ('legal_matters_reviewed', models.BooleanField(default=False)),
                ('related_parties_reviewed', models.BooleanField(default=False)),
                ('audit_documentation_completed', models.BooleanField(default=False)),
                ('review_points_cleared', models.BooleanField(default=False)),
                ('partner_review_completed', models.BooleanField(default=False)),
                ('eqr_completed', models.BooleanField(default=False)),
                ('outstanding_matters', models.TextField(blank=True)),
                ('final_review_notes', models.TextField(blank=True)),
                ('completion_conclusion', models.TextField(blank=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_completion_reviews', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_review', to='engagements.engagement')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
