# Generated by Django 5.2.17 on 2026-10-09 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_license_authority_client_license_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated, e.g. REG-000042.', max_length=30, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('license_authority', models.CharField(blank=True, help_text='Authority that issued the trade/practice license.', max_length=150)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Email Verification'), ('verified', 'Email Verified'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client record created when approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Registration',
                'verbose_name_plural': 'Client Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
