# Generated by Django 5.2.17 on 2026-10-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditschedule',
            name='recurrence_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Repeat interval in months for recurring audits, e.g. 12 for an annual internal audit cycle.', null=True),
        ),
    ]
