# Generated by Django 5.2.17 on 2026-10-09 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0002_engagement_rolled_forward_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated, e.g. RP-000042.', max_length=30, unique=True)),
                ('section', models.CharField(blank=True, help_text="Workpaper or audit area this point relates to, e.g. 'planning-assessment' or 'trial-balance'.", max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('responded', 'Responded'), ('cleared', 'Cleared')], default='open', max_length=20)),
                ('response', models.TextField(blank=True, help_text="The assignee's answer / disposition.")),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_review_points', to=settings.AUTH_USER_MODEL)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_review_points', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_points', to='engagements.engagement')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_review_points', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_review_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Point',
                'verbose_name_plural': 'Review Points',
                'ordering': ['-created_at'],
            },
        ),
    ]
