# Generated by Django 5.2.17 on 2026-09-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('auditor', 'Auditor'), ('manager', 'Manager'), ('staff', 'Staff'), ('guest', 'Guest')], default='staff', max_length=20),
        ),
    ]
