# Generated by Django 5.2.17 on 2026-10-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('auditor', 'Auditor'), ('manager', 'Manager'), ('reviewer', 'Peer Reviewer (Read Only)'), ('staff', 'Staff'), ('guest', 'Guest')], default='staff', max_length=20),
        ),
    ]
